# -*- coding: utf-8 -*-
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
"""
Generate the readme.md with the snippets and docstring
"""
from __future__ import print_function

import datetime
import importlib

import snippets

def get_timestamp():
    return "{0}Z".format(datetime.datetime.utcnow()\
                            .strftime('%Y-%m-%dT%H:%M:%S.%f')[:-3])


header = """
# Python Snippets

A collection of Python function I use daily with examples, lint and tests.

Examples are described in the snippet docstring (in the README too) and could be located in `main` folder.

Tests are done with [tox](http://tox.testrun.org/) using [pytest](http://pytest.org/latest/) and [coverage](https://github.com/pytest-dev/pytest-cov) plugins.

To run the tests:

    $ pip install virtualenv
    $ virtualenv .venv
    $ source .venv/bin/activate
    $ pip install -r requirements.txt
    $ tox
    $ tox -e lint

_**Snippets summary:**_

"""

summary = ""

body = "\n"

footer = """
## License

Licensed under the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License. You may obtain
a copy of the License at http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations
under the License.

---

The README was generated by `gen_readme.py` at {0}
""".format(get_timestamp())



for snippet in snippets.__all__:

    print("Snippet:", snippet)
    m = importlib.import_module("snippets." + snippet)

    raw = "https://raw.githubusercontent.com/ahmet2mir/python-snippets/"\
          "master/snippets/{0}.py".format(snippet)

    title_summary = snippet.capitalize().replace('_', ' ').strip()
    title =  title_summary + " ([download]({0}))".format(raw)

    anchor = title_summary.lower().replace(' ', '-')

    sumas = ""
    for line in m.__doc__.split("\n"):
        sumas += line
        if len(line) < 2:
            break
    suma = sumas.strip().replace("\n", " ")
    print("    summary:", suma)
    

    summary += "* [{0}](#{1}): {2} ([download]({3}))\n"\
               .format(title_summary, anchor, suma, raw)

    body +="## {0}\n([download]({1}))\n\n{2}"\
           .format(title_summary, raw, m.__doc__)


with open('README.md', 'w') as fd:
    fd.write(header + summary + body + footer)

print("README.md generated")